#!/usr/bin/env bash
set -e 

# Runs tsc.
tsc ./index.js --skipLibCheck --noEmit --jsx react-native --esModuleInterop --allowJs --resolveJsonModule

# Runs eslint (and eslint prettier plugin) for the specified extensions.
eslint . --fix --ext .js,.ts,.tsx,.cjs,.mjs --cache

# Additionally format files outside of eslint's scope.
prettier --write "**/*.{json,md,yml,yaml}" .eslintrc.js --cache