/**
 * Do not edit directly
 * Generated on Sun, 07 Jan 2024 04:08:59 GMT
 */

export const backgroundButtonBase = '#dbff00ff'
export const backgroundButtonPressed = '#490448ff'
export const backgroundButtonReflectionBase = '#ffffff00'
export const backgroundButtonReflectionPressed = '#000000ff'
export const backgroundHeaderList = '#dbff00ff'
export const backgroundHeaderDetails = '#dbff00ff'
export const backgroundPillBase = '#490448ff'
export const backgroundSwitchTrackOn = '#490448ff'
export const backgroundSwitchTrackOff = '#ae84aeff'
export const backgroundSwitchThumbOn = '#dbff00ff'
export const backgroundSwitchThumbOff = '#490448ff'
export const backgroundCardReflection = '#000000ff'
export const backgroundSurface100 = '#ffffffff'
export const backgroundSurface200 = '#e6e6e6ff'
export const backgroundOverlay = '#abc70599'
export const borderBase = '#000000ff'
export const borderRatingActive = '#f10e16ff'
export const borderButtonBase = '#000000ff'
export const borderButtonPressed = '#000000ff'
export const borderAccent = '#490448ff'
export const textBase = '#000000ff'
export const textButtonBase = '#000000ff'
export const textButtonPressed = '#dbff00ff'
export const textEmptyBase = '#b3b3b3ff'
export const textAccent = '#490448ff'
export const textPillBase = '#dbff00ff'
